name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ 799579064 }}
        token: ${{ 1155014817:AAHX7Q2lTO0AdLd3QrNenlfw77Wn1PmvDGA }}
        args: The ${{ github.event_name }} event triggered first step.
